### PR TITLE
chore: Update linked-hash-map to 0.5

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by Lesiuk** [comment]
Without this on newest rust this library is panicing

attempted to leave type `linked_hash_map::Node<std::string::String, value::Value>` uninitialized, which is invalid

**Comment by Ten0** [comment]
up

**Comment by Ten0** [comment]
This does not pass CI though

**Comment by tishun** [comment]
@dqsully and @trobro I think this was addressed by #24 so we can close it

**Comment by trobro** [comment]
Thanks, closing.

**Pull request closed without merging**
